version: '3.8'

# Атрибут 'version' устарел и его можно убрать
services:
  app:
    # 'depends_on' больше не нужен, так как сервиса 'db' нет
    image: pavlogook/car-service
    build:
      context: .
    env_file: ./.env
    container_name: app
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:postgresql://ep-red-butterfly-a1ktqoii-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require",
        "spring.datasource.username": "neondb_owner",
        "spring.datasource.password": "npg_crDKwv1pql2G",
        "spring.jpa.hibernate.ddl-auto": "validate"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"